run:
  timeout: 5m
  issues-exit-code: 0
  modules-download-mode: readonly
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: true
  exclude-dirs-use-default: true
  new: true

output:
  formats:
    - format: colored-line-number
      path: stderr
    - format: checkstyle
      path: report.xml